services:
  - type: web
    name: pharm-manager-server
    env: node
    rootDir: server
    # Build from the server directory
    buildCommand: |
      echo "Current directory: $(pwd)"
      echo "Directory contents:"
      ls -la || dir
      echo "Installing dependencies..."
      npm ci --include=dev
      echo "Dependencies installed"
      echo "Building TypeScript..."
      npm run build
      echo "Build completed"
      echo "Checking dist directory:"
      ls -la dist/ || dir dist
      echo "Verifying server.js exists:"
      test -f dist/server.js && echo "✓ server.js found!" || echo "✗ server.js NOT found!"
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: CORS_ORIGIN
        value: "https://medicare-0971.onrender.com" # adjust to your client origin
      - key: COOKIE_DOMAIN
        value: "medicare-0971.onrender.com" # adjust to your domain (not a secret)
      - key: REACT_APP_SOCKET_URL
        value: "hhttps://pharm-manager-api.onrender.com"



