services:
  - type: web
    name: pharm-manager-server
    env: node
    rootDir: ./server
    # Ensure devDependencies (like TypeScript) are installed during build
    # even if NODE_ENV=production is set for runtime. Use npm ci with dev included.
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: CORS_ORIGIN
        value: "https://app.example.com" # adjust to your client origin
      - key: COOKIE_DOMAIN
        value: ".example.com" # adjust to your domain (not a secret)
      - key: REACT_APP_SOCKET_URL
        value: "https://sockets.example.com"



