services:
  - type: web
    name: pharm-manager-server
    env: node
    # Work from project root
    buildCommand: |
      echo "=== BUILD DEBUG INFO ==="
      echo "Current directory: $(pwd)"
      echo "Project root contents:"
      ls -la
      echo "=== NAVIGATING TO SERVER ==="
      cd server
      echo "Server directory: $(pwd)"
      echo "Server contents:"
      ls -la
      echo "=== INSTALLING DEPENDENCIES ==="
      npm ci --include=dev
      echo "=== BUILDING TYPESCRIPT ==="
      npm run build
      echo "=== BUILD VERIFICATION ==="
      echo "Dist contents:"
      ls -la dist/
      echo "Server.js file check:"
      ls -la dist/server.js
      echo "File exists test:"
      test -f dist/server.js && echo "✓ FOUND" || echo "✗ NOT FOUND"
      echo "=== BUILD COMPLETE ==="
    startCommand: |
      echo "=== STARTUP DEBUG INFO ==="
      echo "Startup directory: $(pwd)"
      cd server
      echo "Changed to: $(pwd)"
      echo "Contents:"
      ls -la
      echo "Dist contents:"
      ls -la dist/
      echo "Starting server..."
      node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: CORS_ORIGIN
        value: "https://medicare-0971.onrender.com" # adjust to your client origin
      - key: COOKIE_DOMAIN
        value: "medicare-0971.onrender.com" # adjust to your domain (not a secret)
      - key: REACT_APP_SOCKET_URL
        value: "hhttps://pharm-manager-api.onrender.com"



